
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COM DOISPONTOS ENTAO FACA FIM MOSTRE MULTIPLIQUE NUM PONTO POR REPITA SE SENAO SER SOME VAR VEZES\n    programa : cmds\n    \n    cmds : cmd cmds\n         | cmd\n    \n    cmd : atribuicao\n        | impressao\n        | operacao\n        | repeticao\n        | condicional\n    \n    atribuicao : FACA VAR SER NUM PONTO\n    \n    impressao : MOSTRE VAR PONTO\n              | MOSTRE NUM PONTO\n    \n    operacao : SOME VAR COM VAR PONTO\n             | SOME VAR COM NUM PONTO\n             | SOME NUM COM VAR PONTO\n             | SOME NUM COM NUM PONTO\n    \n    repeticao : REPITA NUM VEZES DOISPONTOS cmds FIM\n    \n    condicional : SE NUM ENTAO cmds FIM\n    \n    condicional : SE NUM ENTAO cmds SENAO cmds FIM\n    \n    operacao : MULTIPLIQUE VAR POR VAR PONTO\n             | MULTIPLIQUE VAR POR NUM PONTO\n             | MULTIPLIQUE NUM POR VAR PONTO\n             | MULTIPLIQUE NUM POR NUM PONTO\n    '
    
_lr_action_items = {'FACA':([0,3,4,5,6,7,8,26,27,33,43,45,46,47,48,49,50,51,52,53,55,56,57,59,],[9,9,-4,-5,-6,-7,-8,-10,-11,9,9,-9,-12,-13,-15,-14,-19,-20,-22,-21,-17,9,-16,-18,]),'MOSTRE':([0,3,4,5,6,7,8,26,27,33,43,45,46,47,48,49,50,51,52,53,55,56,57,59,],[10,10,-4,-5,-6,-7,-8,-10,-11,10,10,-9,-12,-13,-15,-14,-19,-20,-22,-21,-17,10,-16,-18,]),'SOME':([0,3,4,5,6,7,8,26,27,33,43,45,46,47,48,49,50,51,52,53,55,56,57,59,],[11,11,-4,-5,-6,-7,-8,-10,-11,11,11,-9,-12,-13,-15,-14,-19,-20,-22,-21,-17,11,-16,-18,]),'MULTIPLIQUE':([0,3,4,5,6,7,8,26,27,33,43,45,46,47,48,49,50,51,52,53,55,56,57,59,],[12,12,-4,-5,-6,-7,-8,-10,-11,12,12,-9,-12,-13,-15,-14,-19,-20,-22,-21,-17,12,-16,-18,]),'REPITA':([0,3,4,5,6,7,8,26,27,33,43,45,46,47,48,49,50,51,52,53,55,56,57,59,],[13,13,-4,-5,-6,-7,-8,-10,-11,13,13,-9,-12,-13,-15,-14,-19,-20,-22,-21,-17,13,-16,-18,]),'SE':([0,3,4,5,6,7,8,26,27,33,43,45,46,47,48,49,50,51,52,53,55,56,57,59,],[14,14,-4,-5,-6,-7,-8,-10,-11,14,14,-9,-12,-13,-15,-14,-19,-20,-22,-21,-17,14,-16,-18,]),'$end':([1,2,3,4,5,6,7,8,15,26,27,45,46,47,48,49,50,51,52,53,55,57,59,],[0,-1,-3,-4,-5,-6,-7,-8,-2,-10,-11,-9,-12,-13,-15,-14,-19,-20,-22,-21,-17,-16,-18,]),'FIM':([3,4,5,6,7,8,15,26,27,44,45,46,47,48,49,50,51,52,53,54,55,57,58,59,],[-3,-4,-5,-6,-7,-8,-2,-10,-11,55,-9,-12,-13,-15,-14,-19,-20,-22,-21,57,-17,-16,59,-18,]),'SENAO':([3,4,5,6,7,8,15,26,27,44,45,46,47,48,49,50,51,52,53,55,57,59,],[-3,-4,-5,-6,-7,-8,-2,-10,-11,56,-9,-12,-13,-15,-14,-19,-20,-22,-21,-17,-16,-18,]),'VAR':([9,10,11,12,28,29,30,31,],[16,17,19,21,35,38,39,42,]),'NUM':([10,11,12,13,14,25,28,29,30,31,],[18,20,22,23,24,34,36,37,40,41,]),'SER':([16,],[25,]),'PONTO':([17,18,34,35,36,37,38,39,40,41,42,],[26,27,45,46,47,48,49,50,51,52,53,]),'COM':([19,20,],[28,29,]),'POR':([21,22,],[30,31,]),'VEZES':([23,],[32,]),'ENTAO':([24,],[33,]),'DOISPONTOS':([32,],[43,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'cmds':([0,3,33,43,56,],[2,15,44,54,58,]),'cmd':([0,3,33,43,56,],[3,3,3,3,3,]),'atribuicao':([0,3,33,43,56,],[4,4,4,4,4,]),'impressao':([0,3,33,43,56,],[5,5,5,5,5,]),'operacao':([0,3,33,43,56,],[6,6,6,6,6,]),'repeticao':([0,3,33,43,56,],[7,7,7,7,7,]),'condicional':([0,3,33,43,56,],[8,8,8,8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> cmds','programa',1,'p_programa','compilador.py',58),
  ('cmds -> cmd cmds','cmds',2,'p_cmds','compilador.py',65),
  ('cmds -> cmd','cmds',1,'p_cmds','compilador.py',66),
  ('cmd -> atribuicao','cmd',1,'p_cmd','compilador.py',72),
  ('cmd -> impressao','cmd',1,'p_cmd','compilador.py',73),
  ('cmd -> operacao','cmd',1,'p_cmd','compilador.py',74),
  ('cmd -> repeticao','cmd',1,'p_cmd','compilador.py',75),
  ('cmd -> condicional','cmd',1,'p_cmd','compilador.py',76),
  ('atribuicao -> FACA VAR SER NUM PONTO','atribuicao',5,'p_atribuicao','compilador.py',82),
  ('impressao -> MOSTRE VAR PONTO','impressao',3,'p_impressao','compilador.py',88),
  ('impressao -> MOSTRE NUM PONTO','impressao',3,'p_impressao','compilador.py',89),
  ('operacao -> SOME VAR COM VAR PONTO','operacao',5,'p_operacao','compilador.py',95),
  ('operacao -> SOME VAR COM NUM PONTO','operacao',5,'p_operacao','compilador.py',96),
  ('operacao -> SOME NUM COM VAR PONTO','operacao',5,'p_operacao','compilador.py',97),
  ('operacao -> SOME NUM COM NUM PONTO','operacao',5,'p_operacao','compilador.py',98),
  ('repeticao -> REPITA NUM VEZES DOISPONTOS cmds FIM','repeticao',6,'p_repeticao','compilador.py',104),
  ('condicional -> SE NUM ENTAO cmds FIM','condicional',5,'p_condicional','compilador.py',111),
  ('condicional -> SE NUM ENTAO cmds SENAO cmds FIM','condicional',7,'p_condicional_senao','compilador.py',118),
  ('operacao -> MULTIPLIQUE VAR POR VAR PONTO','operacao',5,'p_operacao_mult','compilador.py',126),
  ('operacao -> MULTIPLIQUE VAR POR NUM PONTO','operacao',5,'p_operacao_mult','compilador.py',127),
  ('operacao -> MULTIPLIQUE NUM POR VAR PONTO','operacao',5,'p_operacao_mult','compilador.py',128),
  ('operacao -> MULTIPLIQUE NUM POR NUM PONTO','operacao',5,'p_operacao_mult','compilador.py',129),
]
